/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { sha256 } from './crypto';

// RFC 2409 1024-bit MODP Group 2 Prime
// P = 2^1024 - 2^960 - 1 + 2^64 * { [2^894 pi] + 129090 }
export const PRIME_HEX = 
  "FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD1" +
  "29024E088A67CC74020BBEA63B139B22514A08798E3404DD" +
  "EF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245" +
  "E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7ED" +
  "EE386BFB5A899FA5AE9F24117C4B1FE649286651ECE65381" +
  "FFFFFFFFFFFFFFFF";

export const P = BigInt("0x" + PRIME_HEX);
// Subgroup order for quadratic residues is Q = (P - 1) / 2 which is a prime
export const Q = (P - 1n) / 2n;

/**
 * Performs modular exponentiation: (base ^ exponent) % modulus
 */
export function modPow(base: bigint, exponent: bigint, modulus: bigint): bigint {
  if (modulus === 1n) return 0n;
  let result = 1n;
  let b = ((base % modulus) + modulus) % modulus;
  let e = exponent;
  while (e > 0n) {
    if (e % 2n === 1n) {
      result = (result * b) % modulus;
    }
    e = e / 2n;
    b = (b * b) % modulus;
  }
  return result;
}

/**
 * Generates a cryptographically secure random private exponent in [2, Q-2]
 */
export function generatePrivateExponent(): bigint {
  const array = new Uint8Array(64); // 512-bit random values for extreme security
  let val = 0n;
  do {
    if (typeof window !== 'undefined' && window.crypto) {
      window.crypto.getRandomValues(array);
    } else {
      // Server-side fallback (fallback to crypto package or node crypto if needed, 
      // but client-side carries out the modular math)
      try {
        const crypto = require('crypto');
        const buf = crypto.randomBytes(64);
        array.set(buf);
      } catch (e) {
        // Simple fallback
        for (let i = 0; i < 64; i++) {
          array[i] = Math.floor(Math.random() * 256);
        }
      }
    }
    val = 0n;
    for (const b of array) {
      val = (val << 8n) + BigInt(b);
    }
    val = (val % (Q - 4n)) + 2n;
  } while (val <= 1n || val >= Q);
  return val;
}

/**
 * Hashes a normalized secret to a quadratic residue group element in Z_P*.
 * This ensures the element is in the prime-order subgroup generated by Q.
 */
export async function hashToGroupElement(secret: string): Promise<bigint> {
  const hashHex = await sha256(secret);
  const val = BigInt("0x" + hashHex);
  // Any quadratic residue (val ^ 2 % P) generates the subgroup of prime order Q
  let h = modPow(val, 2n, P);
  if (h === 0n || h === 1n || h === P - 1n) {
    // Standard safe generator fallback
    h = 4n;
  }
  return h;
}
